name: 'Setup environment'
description: 'Sets up local action environment with the necessary components'

runs:
  using: 'composite'
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.75.0

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          src-tauri
        shared-key: base-env

    - name: Check Swift version
      shell: bash
      run: swift --version

#    - name: Broadly locate libswiftCore.dylib
#      shell: bash
#      run: |
#        sudo find / -name libswiftCore.dylib 2>/dev/null

#    # Install Xcode Command Line Tools
#    - name: Install Xcode Command Line Tools
#      shell: bash
#      run: |
#        sudo xcode-select --install || true
#        sudo xcode-select --reset
#
    - name: Set DYLD_LIBRARY_PATH for macOS Swift libraries
      shell: bash
      run: echo "DYLD_LIBRARY_PATH=/Library/Developer/CommandLineTools/usr/lib/swift-5.0/macosx:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Install frontend dependencies
      shell: bash
      run: yarn install