name: "Run unit tests (Rust and Typescript)"
on: pull_request

jobs:
  test-app:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
    runs-on: ${{matrix.platform}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Run Typescript unit tests
        run: yarn test

      - name: Run Rust unit tests
        working-directory: src-tauri
        run: cargo test
